# Generated by Django 4.2.9 on 2024-11-26 19:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='users/user_profile.jpg', upload_to='users/')),
                ('birthday', models.CharField(blank=True, max_length=80, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('gender', models.CharField(blank=True, max_length=80, null=True)),
                ('job', models.CharField(blank=True, max_length=80, null=True)),
                ('telephone', models.CharField(blank=True, max_length=80, null=True)),
                ('biography', models.TextField(blank=True, max_length=400, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfiles',
                'ordering': ['-id'],
            },
        ),
    ]
