# Generated by Django 4.2.9 on 2024-12-13 19:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TypeVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
            ],
            options={
                'verbose_name': 'Tipo de vehiculo',
                'verbose_name_plural': 'Tipo de vehiculos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(default='Neon', max_length=80)),
                ('year', models.CharField(max_length=80)),
                ('color', models.CharField(max_length=80)),
                ('license_vehicle', models.CharField(max_length=80, unique=True)),
                ('transmission', models.CharField(choices=[('manual', 'Manual'), ('automatic', 'Automático')], max_length=80)),
                ('alias', models.CharField(blank=True, max_length=80, null=True)),
                ('number', models.CharField(blank=True, max_length=80, null=True)),
                ('image', models.ImageField(blank=True, default='vehicles/user_profile.jpg', null=True, upload_to='vehicles/')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand', to='vehicle.brand')),
                ('type_vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_vehicle', to='vehicle.typevehicle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vehiculo',
                'verbose_name_plural': 'Vehiculos',
                'ordering': ['id'],
            },
        ),
    ]
