# Generated by Django 4.2.9 on 2024-12-15 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='image',
            field=models.ImageField(blank=True, default='vehicles/neon.jpg', null=True, upload_to='vehicles/'),
        ),
    ]
