# Generated by Django 4.2.9 on 2024-12-16 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0002_alter_vehicle_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='number',
            field=models.CharField(blank=True, max_length=80, null=True, unique=True),
        ),
    ]
