# Generated by Django 4.2.9 on 2024-12-16 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0003_alter_vehicle_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motor', models.CharField(blank=True, default='2.0L 16V', max_length=120, null=True)),
                ('km_actual', models.CharField(blank=True, default='0', max_length=120, null=True)),
                ('oil', models.CharField(blank=True, default='0KM', max_length=120, null=True)),
                ('fuel', models.CharField(blank=True, default='0Lt', max_length=120, null=True)),
                ('break_automobile', models.CharField(blank=True, default='0KM', max_length=120, null=True)),
                ('timing_belt', models.CharField(blank=True, default='0KM', max_length=120, null=True)),
                ('observations', models.TextField(blank=True, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle', to='vehicle.vehicle')),
            ],
            options={
                'verbose_name': 'Mantenimiento',
                'verbose_name_plural': 'Mantenimientos',
                'ordering': ['id'],
            },
        ),
    ]
